# Generated by Django 2.0 on 2018-01-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('attached_file', models.FileField(blank=True, upload_to='article_file/')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('time', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plan', models.TextField(blank=True)),
                ('book', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('exam', models.TextField(blank=True)),
                ('knowledge', models.TextField(blank=True)),
                ('project', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
                ('upload_file', models.FileField(blank=True, upload_to='homework/')),
                ('score', models.IntegerField(default=0)),
                ('evaluation', models.TextField(blank=True)),
                ('checked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('attached_file', models.FileField(blank=True, upload_to='resource/homework/')),
                ('pub_date', models.DateTimeField()),
                ('weight', models.IntegerField()),
                ('ddl', models.DateTimeField()),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Class')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Class')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=50)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='display.PasswordQuestion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('attached_file', models.FileField(upload_to='resource/')),
                ('simple_file', models.FileField(blank=True, upload_to='resource/')),
                ('pub_date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('experience', models.TextField(blank=True)),
                ('research', models.TextField(blank=True)),
                ('style', models.TextField(blank=True)),
                ('publication', models.TextField(blank=True)),
                ('honor', models.TextField(blank=True)),
                ('contact', models.TextField(blank=True)),
                ('other', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Teacher'),
        ),
        migrations.AddField(
            model_name='notification',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Teacher'),
        ),
        migrations.AddField(
            model_name='join',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Student'),
        ),
        migrations.AddField(
            model_name='finish',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Homework'),
        ),
        migrations.AddField(
            model_name='finish',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Course'),
        ),
        migrations.AddField(
            model_name='article',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.Teacher'),
        ),
    ]
