# Generated by Django 2.0 on 2018-01-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('g_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_host', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Iviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_content', models.CharField(max_length=3000)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iviation_from', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iviation_group', to='discuss.GroupList')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iviation_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=20)),
                ('p_content', models.CharField(max_length=3000)),
                ('p_time', models.DateTimeField()),
                ('p_read', models.IntegerField()),
                ('p_rc', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_group', to='discuss.GroupList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('guest', models.CharField(max_length=10, null=True)),
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_content', models.CharField(max_length=3000)),
                ('r_time', models.DateTimeField()),
                ('r_rk', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_posts', to='discuss.Posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
